name: CI/CD

on:
  push:
    branches: [ main, master ]
    tags: [ "v*", "release-*" ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint & Smoke Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-serve.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install runtime deps (only requirements-serve.txt)
        run: |
          pip install --upgrade pip
          pip install -r requirements-serve.txt
          pip install pytest flake8  # optional tools for this job

      - name: Lint
        run: flake8 . || true

      - name: Smoke test import
        run: python -c "import sys; print('OK: deps load')"

  docker:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: catdog-serve
      DOCKERFILE_PATH: Dockerfile.mlflow
    steps:
      - uses: actions/checkout@v4

      - id: lc
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional Docker Hub login (if you also push there)
      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.lc.outputs.owner }}/catdogcicd/${{ env.IMAGE_NAME }}
            ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN && format('{0}/{1}', secrets.DOCKERHUB_USERNAME, env.IMAGE_NAME) || '' }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}},enable={{is_tag}}
            type=semver,pattern={{major}}.{{minor}},enable={{is_tag}}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max